app:
  name: "playground-go-websocket"
  echoPort: "8081"
  ginPort: "8082"
  version: "1.0.0"
  trustProxies:
    - "127.0.0.1"
  upgrader:
    readBufferSize: 1024
    writeBufferSize: 1024

log:
  level: "debug"


